#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from phase3.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "phase3.y"

	#include <stdio.h>
    extern int yylex();
    extern int yyparse();
    extern FILE *yyin;
    FILE * fout;
    void yyerror(const char *s);
    extern int yylineno;
    extern char* yytext;
    #define YYERROR_VERBOSE 1

#line 24 "phase3.y"
typedef union{
    char *str;
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	MAIN	258
#define	INT	259
#define	CHAR	260
#define	IF	261
#define	ELSE	262
#define	ELSEIF	263
#define	WHILE	264
#define	CONTINUE	265
#define	BREAK	266
#define	FOR	267
#define	RETURN	268
#define	VOID	269
#define	IDENTIFIER	270
#define	INT_CONST	271
#define	CHAR_CONST	272
#define	DOT	273
#define	COMMA	274
#define	ISLESSEQ	275
#define	ISMOREQ	276
#define	ISEQL	277
#define	ISNEQL	278
#define	ASSIGN	279
#define	LEFTB	280
#define	RIGHTB	281
#define	OR	282
#define	ORBIT	283
#define	AND	284
#define	ANDBIT	285
#define	XORBIT	286
#define	NOT	287
#define	PLUS	288
#define	MINUS	289
#define	MULTIPLY	290
#define	DIVIDE	291
#define	LEFTPAREN	292
#define	RIGHTPAREN	293
#define	LEFTBRACE	294
#define	RIGHTBRACE	295


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int MAIN;
static const int INT;
static const int CHAR;
static const int IF;
static const int ELSE;
static const int ELSEIF;
static const int WHILE;
static const int CONTINUE;
static const int BREAK;
static const int FOR;
static const int RETURN;
static const int VOID;
static const int IDENTIFIER;
static const int INT_CONST;
static const int CHAR_CONST;
static const int DOT;
static const int COMMA;
static const int ISLESSEQ;
static const int ISMOREQ;
static const int ISEQL;
static const int ISNEQL;
static const int ASSIGN;
static const int LEFTB;
static const int RIGHTB;
static const int OR;
static const int ORBIT;
static const int AND;
static const int ANDBIT;
static const int XORBIT;
static const int NOT;
static const int PLUS;
static const int MINUS;
static const int MULTIPLY;
static const int DIVIDE;
static const int LEFTPAREN;
static const int RIGHTPAREN;
static const int LEFTBRACE;
static const int RIGHTBRACE;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,MAIN=258
	,INT=259
	,CHAR=260
	,IF=261
	,ELSE=262
	,ELSEIF=263
	,WHILE=264
	,CONTINUE=265
	,BREAK=266
	,FOR=267
	,RETURN=268
	,VOID=269
	,IDENTIFIER=270
	,INT_CONST=271
	,CHAR_CONST=272
	,DOT=273
	,COMMA=274
	,ISLESSEQ=275
	,ISMOREQ=276
	,ISEQL=277
	,ISNEQL=278
	,ASSIGN=279
	,LEFTB=280
	,RIGHTB=281
	,OR=282
	,ORBIT=283
	,AND=284
	,ANDBIT=285
	,XORBIT=286
	,NOT=287
	,PLUS=288
	,MINUS=289
	,MULTIPLY=290
	,DIVIDE=291
	,LEFTPAREN=292
	,RIGHTPAREN=293
	,LEFTBRACE=294
	,RIGHTBRACE=295


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::MAIN=258;
const int YY_parse_CLASS::INT=259;
const int YY_parse_CLASS::CHAR=260;
const int YY_parse_CLASS::IF=261;
const int YY_parse_CLASS::ELSE=262;
const int YY_parse_CLASS::ELSEIF=263;
const int YY_parse_CLASS::WHILE=264;
const int YY_parse_CLASS::CONTINUE=265;
const int YY_parse_CLASS::BREAK=266;
const int YY_parse_CLASS::FOR=267;
const int YY_parse_CLASS::RETURN=268;
const int YY_parse_CLASS::VOID=269;
const int YY_parse_CLASS::IDENTIFIER=270;
const int YY_parse_CLASS::INT_CONST=271;
const int YY_parse_CLASS::CHAR_CONST=272;
const int YY_parse_CLASS::DOT=273;
const int YY_parse_CLASS::COMMA=274;
const int YY_parse_CLASS::ISLESSEQ=275;
const int YY_parse_CLASS::ISMOREQ=276;
const int YY_parse_CLASS::ISEQL=277;
const int YY_parse_CLASS::ISNEQL=278;
const int YY_parse_CLASS::ASSIGN=279;
const int YY_parse_CLASS::LEFTB=280;
const int YY_parse_CLASS::RIGHTB=281;
const int YY_parse_CLASS::OR=282;
const int YY_parse_CLASS::ORBIT=283;
const int YY_parse_CLASS::AND=284;
const int YY_parse_CLASS::ANDBIT=285;
const int YY_parse_CLASS::XORBIT=286;
const int YY_parse_CLASS::NOT=287;
const int YY_parse_CLASS::PLUS=288;
const int YY_parse_CLASS::MINUS=289;
const int YY_parse_CLASS::MULTIPLY=290;
const int YY_parse_CLASS::DIVIDE=291;
const int YY_parse_CLASS::LEFTPAREN=292;
const int YY_parse_CLASS::RIGHTPAREN=293;
const int YY_parse_CLASS::LEFTBRACE=294;
const int YY_parse_CLASS::RIGHTBRACE=295;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		199
#define	YYFLAG		-32768
#define	YYNTBASE	41

#define YYTRANSLATE(x) ((unsigned)(x) <= 295 ? yytranslate[x] : 102)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     1,     3,     6,     7,    14,    15,    20,    23,    25,
    27,    29,    31,    33,    36,    40,    43,    46,    47,    48,
    49,    58,    59,    60,    61,    72,    73,    74,    75,    89,
    90,    91,    92,   109,   110,   116,   117,   125,   126,   136,
   138,   140,   142,   144,   145,   146,   152,   154,   155,   156,
   162,   163,   164,   170,   171,   176,   177,   182,   183,   188,
   189,   194,   195,   200,   201,   206,   207,   212,   213,   218,
   219,   224,   225,   230,   232,   234,   236,   238,   242,   247,
   249,   251,   253,   255,   257,   259,   260,   268,   269,   270,
   274,   275,   280,   283,   285,   286,   293,   294,   295,   303,
   304,   305
};

static const short yyrhs[] = {    -1,
    42,     0,    48,    42,     0,     0,     4,     3,    37,    38,
    43,    44,     0,     0,    25,    46,    45,    26,     0,    47,
    46,     0,    47,     0,    88,     0,    99,     0,    96,     0,
    67,     0,    73,    18,     0,    13,    76,    18,     0,    11,
    18,     0,    10,    18,     0,     0,     0,     0,    65,    49,
    15,    50,    37,    51,    38,    44,     0,     0,     0,     0,
    65,    52,    15,    53,    37,    54,    65,    15,    38,    44,
     0,     0,     0,     0,    65,    55,    15,    56,    37,    57,
    65,    15,    19,    65,    15,    38,    44,     0,     0,     0,
     0,    65,    58,    15,    59,    37,    60,    65,    15,    19,
    65,    15,    19,    65,    15,    38,    44,     0,     0,    15,
    62,    37,    76,    38,     0,     0,    15,    63,    37,    76,
    19,    76,    38,     0,     0,    15,    64,    37,    76,    19,
    76,    19,    76,    38,     0,    14,     0,    66,     0,     5,
     0,     4,     0,     0,     0,    66,    68,    15,    69,    70,
     0,    18,     0,     0,     0,    24,    71,    76,    72,    18,
     0,     0,     0,    15,    74,    24,    75,    76,     0,     0,
    76,    33,    77,    76,     0,     0,    76,    34,    78,    76,
     0,     0,    76,    35,    79,    76,     0,     0,    76,    36,
    80,    76,     0,     0,    76,    30,    81,    76,     0,     0,
    76,    28,    82,    76,     0,     0,    76,    31,    83,    76,
     0,     0,    76,    29,    84,    76,     0,     0,    76,    27,
    85,    76,     0,     0,    76,    87,    86,    76,     0,    16,
     0,    17,     0,    15,     0,    61,     0,    37,    76,    38,
     0,    32,    37,    76,    38,     0,    25,     0,    26,     0,
    20,     0,    21,     0,    22,     0,    23,     0,     0,     6,
    37,    76,    38,    89,    44,    90,     0,     0,     0,     7,
    91,    44,     0,     0,    93,     7,    92,    44,     0,    94,
    93,     0,    94,     0,     0,     8,    37,    76,    38,    95,
    44,     0,     0,     0,    97,     9,    37,    76,    38,    98,
    44,     0,     0,     0,    12,    37,   100,    67,    76,   101,
    18,    73,    38,    44,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    29,    29,    32,    32,    32,    34,    34,    36,    36,    39,
    39,    40,    41,    42,    43,    44,    45,    48,    48,    48,
    48,    48,    49,    49,    49,    49,    50,    50,    50,    50,
    51,    51,    51,    53,    53,    53,    54,    54,    55,    57,
    57,    60,    60,    63,    63,    63,    65,    65,    66,    66,
    68,    68,    68,    70,    70,    70,    71,    71,    72,    72,
    73,    73,    74,    74,    75,    75,    76,    76,    77,    77,
    78,    78,    79,    79,    80,    81,    82,    83,    84,    87,
    87,    88,    89,    90,    91,    94,    94,    96,    96,    97,
    97,    98,   100,   100,   103,   103,   105,   105,   105,   107,
   107,   107
};

static const char * const yytname[] = {   "$","error","$illegal.","MAIN","INT",
"CHAR","IF","ELSE","ELSEIF","WHILE","CONTINUE","BREAK","FOR","RETURN","VOID",
"IDENTIFIER","INT_CONST","CHAR_CONST","DOT","COMMA","ISLESSEQ","ISMOREQ","ISEQL",
"ISNEQL","ASSIGN","LEFTB","RIGHTB","OR","ORBIT","AND","ANDBIT","XORBIT","NOT",
"PLUS","MINUS","MULTIPLY","DIVIDE","LEFTPAREN","RIGHTPAREN","LEFTBRACE","RIGHTBRACE",
"S","M","@1","BSTMTSB","@2","STMTS","STMT","FUNC","@3","@4","@5","@6","@7","@8",
"@9","@10","@11","@12","@13","@14","FUNCCALL","@15","@16","@17","TYPEF","TYPED",
"VARDEF","@18","@19","VARDEFFIN","@20","@21","STEP","@22","@23","EXPR","@24",
"@25","@26","@27","@28","@29","@30","@31","@32","@33","COMPOP","IFSTMT","@34",
"IFSTMTEND","@35","@36","ELIFSTMTS","ELIFSTMT","@37","WHILESTMT","@38","@39",
"FORSTMT","@40","@41",""
};
#endif

static const short yyr1[] = {     0,
    41,    41,    42,    43,    42,    45,    44,    46,    46,    47,
    47,    47,    47,    47,    47,    47,    47,    49,    50,    51,
    48,    52,    53,    54,    48,    55,    56,    57,    48,    58,
    59,    60,    48,    62,    61,    63,    61,    64,    61,    65,
    65,    66,    66,    68,    69,    67,    70,    71,    72,    70,
    74,    75,    73,    77,    76,    78,    76,    79,    76,    80,
    76,    81,    76,    82,    76,    83,    76,    84,    76,    85,
    76,    86,    76,    76,    76,    76,    76,    76,    76,    87,
    87,    87,    87,    87,    87,    89,    88,    90,    91,    90,
    92,    90,    93,    93,    95,    94,    97,    98,    96,   100,
   101,    99
};

static const short yyr2[] = {     0,
     0,     1,     2,     0,     6,     0,     4,     2,     1,     1,
     1,     1,     1,     2,     3,     2,     2,     0,     0,     0,
     8,     0,     0,     0,    10,     0,     0,     0,    13,     0,
     0,     0,    16,     0,     5,     0,     7,     0,     9,     1,
     1,     1,     1,     0,     0,     5,     1,     0,     0,     5,
     0,     0,     5,     0,     4,     0,     4,     0,     4,     0,
     4,     0,     4,     0,     4,     0,     4,     0,     4,     0,
     4,     0,     4,     1,     1,     1,     1,     3,     4,     1,
     1,     1,     1,     1,     1,     0,     7,     0,     0,     3,
     0,     4,     2,     1,     0,     6,     0,     0,     7,     0,
     0,    10
};

static const short yydefact[] = {     1,
    43,    42,    40,     2,     0,    18,    41,     0,     3,     0,
     0,     0,     0,     0,    19,    23,    27,    31,     4,     0,
     0,     0,     0,     0,    20,    24,    28,    32,    97,     5,
     0,     0,     0,     0,    43,     0,     0,     0,     0,     0,
    51,     6,     9,    44,    13,     0,    10,    12,     0,    11,
     0,     0,     0,     0,     0,    17,    16,   100,    76,    74,
    75,     0,     0,    77,     0,     0,     0,     8,     0,    14,
     0,    21,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,    15,    82,    83,    84,    85,    80,    81,    70,
    64,    68,    62,    66,    54,    56,    58,    60,    72,    52,
     7,    45,     0,     0,     0,     0,    86,     0,     0,     0,
     0,     0,    78,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,    25,     0,     0,     0,
   101,     0,     0,     0,    79,    71,    65,    69,    63,    67,
    55,    57,    59,    61,    73,    53,    47,    48,    46,    98,
     0,     0,    88,     0,    35,     0,     0,     0,     0,     0,
     0,    89,     0,    87,     0,    94,     0,     0,     0,    49,
    99,    29,     0,     0,     0,    91,    93,     0,    37,     0,
     0,     0,    90,     0,     0,     0,     0,    50,     0,    95,
    92,   102,    39,    33,     0,    96,     0,     0,     0
};

static const short yydefgoto[] = {   197,
     4,    24,    30,    67,    42,    43,     5,    10,    20,    31,
    11,    21,    32,    12,    22,    33,    13,    23,    34,    64,
    78,    79,    80,     6,     7,    45,    69,   125,   149,   158,
   181,    46,    66,   124,    65,   119,   120,   121,   122,   117,
   115,   118,   116,   114,   123,    99,    47,   130,   164,   174,
   185,   165,   166,   195,    48,    49,   159,    50,    77,   154
};

static const short yypact[] = {     0,
    10,-32768,-32768,-32768,     0,-32768,-32768,   -14,-32768,    12,
    16,    18,    31,    17,-32768,-32768,-32768,-32768,-32768,    32,
    43,    44,    45,    62,-32768,-32768,-32768,-32768,   375,-32768,
    50,    47,    47,    47,-32768,    67,    89,    92,    78,    -8,
-32768,-32768,     6,-32768,-32768,   110,-32768,-32768,   127,-32768,
    62,   122,   124,   125,    -8,-32768,-32768,-32768,   104,-32768,
-32768,   105,    -8,-32768,    14,   119,   120,-32768,   130,-32768,
   111,-32768,   109,   144,   149,    91,    21,   112,   137,   145,
    -8,   131,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,    -8,    62,    47,    47,-32768,    -8,    -8,    -8,
    -8,   150,-32768,    -8,    -8,    -8,    -8,    -8,    -8,    -8,
    -8,    -8,    -8,    -8,     4,   169,-32768,   172,   178,    62,
    37,   188,   265,   283,-32768,   347,    80,   347,    80,    80,
   318,   318,   335,   335,    37,    37,-32768,-32768,-32768,-32768,
   163,   187,    69,   194,-32768,    -8,    -8,    -8,    62,    62,
    47,-32768,   183,-32768,   218,   223,   224,   207,   301,    37,
-32768,-32768,   229,    62,    -8,-32768,-32768,   212,-32768,    -8,
   240,   225,-32768,   226,    62,    62,   245,-32768,    62,-32768,
-32768,-32768,-32768,-32768,    62,-32768,   269,   277,-32768
};

static const short yypgoto[] = {-32768,
   284,-32768,   -51,-32768,   239,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,   -31,   -23,   220,-32768,-32768,-32768,-32768,
-32768,   140,-32768,-32768,   -25,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,   159,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768
};


#define	YYLAST		390


static const short yytable[] = {    72,
    52,    53,    54,     1,     2,    44,    59,    60,    61,    35,
     2,    36,     8,     3,   -97,    37,    38,    39,    40,    44,
    41,   147,    14,    62,    35,     2,    15,   148,    63,    76,
    16,    83,    17,    84,    85,    86,    87,    82,    88,    89,
    90,    91,    92,    93,    94,    18,    95,    96,    97,    98,
    35,     2,   127,    44,    19,   112,    84,    85,    86,    87,
     3,    88,    89,    90,    91,    92,    93,    94,    25,    95,
    96,    97,    98,   128,   129,   162,   163,   126,   153,    26,
    27,    28,   131,   132,   133,   134,    29,    51,   136,   137,
   138,   139,   140,   141,   142,   143,   144,   145,   146,    84,
    85,    86,    87,    55,    88,    89,    56,   171,   172,    57,
    84,    85,    86,    87,    58,    88,    89,    90,    91,    92,
    93,    94,   183,    95,    96,    97,    98,    70,   107,   173,
   168,   169,   170,   191,   192,    71,    73,   194,    74,    75,
   -34,    81,   100,   196,   102,   101,   104,   103,   109,   184,
    84,    85,    86,    87,   187,    88,    89,    90,    91,    92,
    93,    94,   105,    95,    96,    97,    98,   106,   113,    84,
    85,    86,    87,   110,    88,    89,    90,    91,    92,    93,
    94,   111,    95,    96,    97,    98,   151,   135,    84,    85,
    86,    87,   152,    88,    89,    90,    91,    92,    93,    94,
   160,    95,    96,    97,    98,   161,   150,    84,    85,    86,
    87,   167,    88,    89,    90,    91,    92,    93,    94,   175,
    95,    96,    97,    98,   176,   155,    84,    85,    86,    87,
   163,    88,    89,    90,    91,    92,    93,    94,    41,    95,
    96,    97,    98,   182,   179,    84,    85,    86,    87,   186,
    88,    89,    90,    91,    92,    93,    94,   188,    95,    96,
    97,    98,   189,   190,    84,    85,    86,    87,   198,    88,
    89,    90,    91,    92,    93,    94,   199,    95,    96,    97,
    98,    68,   193,   156,    84,    85,    86,    87,     9,    88,
    89,    90,    91,    92,    93,    94,   108,    95,    96,    97,
    98,   157,    84,    85,    86,    87,   178,    88,    89,    90,
    91,    92,    93,    94,     0,    95,    96,    97,    98,   180,
    84,    85,    86,    87,   177,    88,    89,    90,    91,    92,
    93,    94,     0,    95,    96,    97,    98,    84,    85,    86,
    87,     0,    88,    89,    90,    91,    92,    93,    94,     0,
     0,     0,    97,    98,    84,    85,    86,    87,     0,    88,
    89,    90,    91,    92,    93,    94,    84,    85,    86,    87,
     0,    88,    89,     0,    91,     0,    93,    94,    35,     2,
    36,     0,     0,     0,    37,    38,    39,    40,     0,    41
};

static const short yycheck[] = {    51,
    32,    33,    34,     4,     5,    29,    15,    16,    17,     4,
     5,     6,     3,    14,     9,    10,    11,    12,    13,    43,
    15,    18,    37,    32,     4,     5,    15,    24,    37,    55,
    15,    18,    15,    20,    21,    22,    23,    63,    25,    26,
    27,    28,    29,    30,    31,    15,    33,    34,    35,    36,
     4,     5,   104,    77,    38,    81,    20,    21,    22,    23,
    14,    25,    26,    27,    28,    29,    30,    31,    37,    33,
    34,    35,    36,   105,   106,     7,     8,   103,   130,    37,
    37,    37,   108,   109,   110,   111,    25,    38,   114,   115,
   116,   117,   118,   119,   120,   121,   122,   123,   124,    20,
    21,    22,    23,    37,    25,    26,    18,   159,   160,    18,
    20,    21,    22,    23,    37,    25,    26,    27,    28,    29,
    30,    31,   174,    33,    34,    35,    36,    18,    38,   161,
   156,   157,   158,   185,   186,     9,    15,   189,    15,    15,
    37,    37,    24,   195,    15,    26,    38,    37,    37,   175,
    20,    21,    22,    23,   180,    25,    26,    27,    28,    29,
    30,    31,    19,    33,    34,    35,    36,    19,    38,    20,
    21,    22,    23,    37,    25,    26,    27,    28,    29,    30,
    31,    37,    33,    34,    35,    36,    15,    38,    20,    21,
    22,    23,    15,    25,    26,    27,    28,    29,    30,    31,
    38,    33,    34,    35,    36,    19,    38,    20,    21,    22,
    23,    18,    25,    26,    27,    28,    29,    30,    31,    37,
    33,    34,    35,    36,     7,    38,    20,    21,    22,    23,
     8,    25,    26,    27,    28,    29,    30,    31,    15,    33,
    34,    35,    36,    15,    38,    20,    21,    22,    23,    38,
    25,    26,    27,    28,    29,    30,    31,    18,    33,    34,
    35,    36,    38,    38,    20,    21,    22,    23,     0,    25,
    26,    27,    28,    29,    30,    31,     0,    33,    34,    35,
    36,    43,    38,    19,    20,    21,    22,    23,     5,    25,
    26,    27,    28,    29,    30,    31,    77,    33,    34,    35,
    36,    19,    20,    21,    22,    23,   167,    25,    26,    27,
    28,    29,    30,    31,    -1,    33,    34,    35,    36,    19,
    20,    21,    22,    23,   166,    25,    26,    27,    28,    29,
    30,    31,    -1,    33,    34,    35,    36,    20,    21,    22,
    23,    -1,    25,    26,    27,    28,    29,    30,    31,    -1,
    -1,    -1,    35,    36,    20,    21,    22,    23,    -1,    25,
    26,    27,    28,    29,    30,    31,    20,    21,    22,    23,
    -1,    25,    26,    -1,    28,    -1,    30,    31,     4,     5,
     6,    -1,    -1,    -1,    10,    11,    12,    13,    -1,    15
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 29 "phase3.y"
{yyerror("EMPTY FILE");;
    break;}
case 2:
#line 30 "phase3.y"
{printf("\n\tCode Successfuly Parsed!\n");;
    break;}
case 4:
#line 32 "phase3.y"
{openScope();;
    break;}
case 6:
#line 34 "phase3.y"
{closeScope();;
    break;}
case 18:
#line 48 "phase3.y"
{setType();;
    break;}
case 19:
#line 48 "phase3.y"
{functionDeclare();;
    break;}
case 20:
#line 48 "phase3.y"
{openScope();;
    break;}
case 22:
#line 49 "phase3.y"
{setType();;
    break;}
case 23:
#line 49 "phase3.y"
{functionDeclare();;
    break;}
case 24:
#line 49 "phase3.y"
{openScope();;
    break;}
case 26:
#line 50 "phase3.y"
{setType();;
    break;}
case 27:
#line 50 "phase3.y"
{functionDeclare();;
    break;}
case 28:
#line 50 "phase3.y"
{openScope();;
    break;}
case 30:
#line 51 "phase3.y"
{setType();;
    break;}
case 31:
#line 51 "phase3.y"
{functionDeclare();;
    break;}
case 32:
#line 51 "phase3.y"
{openScope();;
    break;}
case 34:
#line 53 "phase3.y"
{checkFunc(); call();;
    break;}
case 36:
#line 54 "phase3.y"
{checkFunc(); call();;
    break;}
case 38:
#line 55 "phase3.y"
{checkFunc(); call();;
    break;}
case 44:
#line 63 "phase3.y"
{setType();;
    break;}
case 45:
#line 63 "phase3.y"
{symbolDeclare(yytext);;
    break;}
case 47:
#line 65 "phase3.y"
{pop();;
    break;}
case 48:
#line 66 "phase3.y"
{push(yytext);;
    break;}
case 49:
#line 66 "phase3.y"
{assignCG();;
    break;}
case 51:
#line 68 "phase3.y"
{checkPushSymbol(yytext);;
    break;}
case 52:
#line 68 "phase3.y"
{push(yytext);;
    break;}
case 53:
#line 68 "phase3.y"
{assignCG();;
    break;}
case 54:
#line 70 "phase3.y"
{push(yytext);;
    break;}
case 55:
#line 70 "phase3.y"
{operationCG();;
    break;}
case 56:
#line 71 "phase3.y"
{push(yytext);;
    break;}
case 57:
#line 71 "phase3.y"
{operationCG();;
    break;}
case 58:
#line 72 "phase3.y"
{push(yytext);;
    break;}
case 59:
#line 72 "phase3.y"
{operationCG();;
    break;}
case 60:
#line 73 "phase3.y"
{push(yytext);;
    break;}
case 61:
#line 73 "phase3.y"
{operationCG();;
    break;}
case 62:
#line 74 "phase3.y"
{push(yytext);;
    break;}
case 63:
#line 74 "phase3.y"
{operationCG();;
    break;}
case 64:
#line 75 "phase3.y"
{push(yytext);;
    break;}
case 65:
#line 75 "phase3.y"
{operationCG();;
    break;}
case 66:
#line 76 "phase3.y"
{push(yytext);;
    break;}
case 67:
#line 76 "phase3.y"
{operationCG();;
    break;}
case 68:
#line 77 "phase3.y"
{push(yytext);;
    break;}
case 69:
#line 77 "phase3.y"
{operationCG();;
    break;}
case 70:
#line 78 "phase3.y"
{push(yytext);;
    break;}
case 71:
#line 78 "phase3.y"
{operationCG();;
    break;}
case 72:
#line 79 "phase3.y"
{push(yytext);;
    break;}
case 73:
#line 79 "phase3.y"
{operationCG();;
    break;}
case 74:
#line 80 "phase3.y"
{printf("*\trule INT_CONST %s\n", yyvsp[0]); push(yytext);;
    break;}
case 75:
#line 81 "phase3.y"
{printf("*\trule CHAR_CONST %s\n", yyvsp[0]); push(yytext);;
    break;}
case 76:
#line 82 "phase3.y"
{printf("*\trule IDENTIFIER %s\n", yyvsp[0]); checkPushSymbol(yyvsp[0]);;
    break;}
case 86:
#line 94 "phase3.y"
{labelIfStart(); openScope();;
    break;}
case 88:
#line 96 "phase3.y"
{labelIfFinish();;
    break;}
case 89:
#line 97 "phase3.y"
{labelElse(); openScope();;
    break;}
case 90:
#line 97 "phase3.y"
{labelIfFinish();;
    break;}
case 91:
#line 98 "phase3.y"
{labelElse(); openScope();;
    break;}
case 92:
#line 98 "phase3.y"
{labelIfFinish();;
    break;}
case 95:
#line 103 "phase3.y"
{labelElse(); labelElseIfStart(); openScope();;
    break;}
case 97:
#line 105 "phase3.y"
{labelWhileStart();;
    break;}
case 98:
#line 105 "phase3.y"
{openScope(); labelWhileRepeat();;
    break;}
case 99:
#line 105 "phase3.y"
{labelWhileFinish();;
    break;}
case 100:
#line 107 "phase3.y"
{labelWhileStart(); openScope();;
    break;}
case 101:
#line 107 "phase3.y"
{labelWhileRepeat();;
    break;}
case 102:
#line 107 "phase3.y"
{labelWhileFinish();;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 109 "phase3.y"



int count = 0;
char stack[1000][10];
int stackTop = 0;
char tempVar[3] = "t";
int labels[1000];
int labelCount = 0;
int labelTop = 0;
int tempCount = 0;
char tmpType[10];

struct symbolTableEntity {
	char id[20];
	char type[10];
} symbolTable[10000];

int symbolTableCount = 1;

struct functionTableEntity {
	char id[20];
	char type[10];
    char label[5];
} functionTable[100];

int functionTableCount = 0;

void yyerror(const char *s){
    printf("\n\tError %s in line %d\n\n", s, yylineno);
    //printf("\n\tError %s in line %d: %s\n\n", s, yylineno, yytext);
    //fprintf(stderr,"\n\tError: %s in line %d\n", s, yylineno - 1);
	//printf ("\n\tError: %s\n", s);
}

int yywrap() {
	return 1;
}

void push(char * val) {
    char tmp[20];
    strcpy(tmp, val);
    printf("Pushing %s\n", tmp);
    if (tmp[0] == '+') strcpy(stack[++stackTop], "add");
    else if (tmp[0] == '-') strcpy(stack[++stackTop], "sub");
    else if (tmp[0] == '*') strcpy(stack[++stackTop], "mul");
    else if (tmp[0] == '/') strcpy(stack[++stackTop], "div");
    else if (tmp[0] == '&') strcpy(stack[++stackTop], "and");
    else if (tmp[0] == '|') strcpy(stack[++stackTop], "or");
    else if (tmp[0] == '^') strcpy(stack[++stackTop], "xor");
    else if (tmp[0] == '<') {
        if (tmp[1] == '=') strcpy(stack[++stackTop], "sle");
        else strcpy(stack[++stackTop], "slt");
    }
    else if (tmp[0] == '>') {
        if (tmp[1] == '=') strcpy(stack[++stackTop], "sge");
        else strcpy(stack[++stackTop], "sgt");
    }
    else if (tmp[1] == '=') {
        if (tmp[0] == '=') strcpy(stack[++stackTop], "seq");
        else if (tmp[0] == '!') strcpy(stack[++stackTop], "sne");
    }
    else strcpy(stack[++stackTop], val);
    printf("\n\tStack: ");
    for (int i = 1; i <= stackTop; i++) {
        printf(" %s,", stack[i]);
    }
    printf("\n\n");
}

void pop() {
    printf("popping %s\n", stack[stackTop]);
    stackTop--;
    printf("\n\tStack: ");
    for (int i = 1; i <= stackTop; i++) {
        printf(" %s,", stack[i]);
    }
    printf("\n\n");
}

void operationCG() { //codegen_logical //codegen_algebric
    sprintf(tempVar, "$t%d", tempCount);
 	tempCount++;
  	fprintf(fout, "\t%s,\t %s,\t %s,\t %s\n", stack[stackTop-1], tempVar, stack[stackTop-2], stack[stackTop]);
  	printf("\t%s,\t %s,\t %s,\t %s\n", stack[stackTop-1], tempVar, stack[stackTop-2], stack[stackTop]);
    stackTop -= 2;
 	strcpy(stack[stackTop], tempVar);
}

void assignCG() { //codegen_assign
    if (stack[stackTop][0] == '$' || (stack[stackTop][0] >= 'a' && stack[stackTop][0] <= 'z') || (stack[stackTop][0] >= 'A' && stack[stackTop][0] <= 'Z')) {
     	fprintf(fout,"\tmov,\t %s,\t %s\n", stack[stackTop-2], stack[stackTop]);
     	printf("\tmov,\t %s,\t %s\n", stack[stackTop-2], stack[stackTop]);
    }
    else {
        fprintf(fout,"\tli,\t %s,\t %s\n", stack[stackTop-2], stack[stackTop]);
        printf("\tli,\t %s,\t %s\n", stack[stackTop-2], stack[stackTop]);
    }
 	stackTop -= 3;
}

void labelIfStart() { // push label
    printf("labelIfStart()\n");
 	labelCount++;
 	fprintf(fout, "\tbeqz,\t %s,\t $L%d\n", stack[stackTop], labelCount);
 	printf("\tbeqz,\t %s,\t $L%d\n", stack[stackTop], labelCount);
 	labels[++labelTop] = labelCount;
    printf("\n\tlabelStack: ");
    for (int i = 0; i <= labelTop; i++) {
        printf(" %d,", labels[i]);
    }
    printf("\n\n");
}

void labelElse() { // pop a label, push another label
    printf("labelElse()\n");
	int tmp;
	labelCount++;
	tmp = labels[labelTop--]; 
	fprintf(fout,"\tjmp,\t $L%d\n$L%d:\n", labelCount, tmp);
	printf("\tjmp,\t $L%d\n$L%d:\n", labelCount, tmp);
	labels[++labelTop] = labelCount;
    printf("\n\tlabelStack: ");
    for (int i = 0; i <= labelTop; i++) {
        printf(" %d,", labels[i]);
    }
    printf("\n\n");
}

void labelElseIfStart() {
    printf("labelElseIfStart()\n");
 	fprintf(fout, "\tbeqz,\t %s,\t $L%d\n", stack[stackTop], labels[labelTop]);
 	printf("\tbeqz,\t %s,\t $L%d\n", stack[stackTop], labels[labelTop]);
    printf("\n\tlabelStack: ");
    for (int i = 0; i <= labelTop; i++) {
        printf(" %d,", labels[i]);
    }
    printf("\n\n");
}

void labelIfFinish() { // pop label
    printf("labelIfFinish()\n");
	int tmp;
	tmp = labels[labelTop--];
	fprintf(fout,"$L%d:\n", tmp);
	printf("$L%d:\n", tmp);
	stackTop--;
    printf("\n\tlabelStack: ");
    for (int i = 0; i <= labelTop; i++) {
        printf(" %d,", labels[i]);
    }
    printf("\n\n");
}

void labelWhileStart() {
    printf("labelWhileStart()\n");
	labels[++labelTop] = ++labelCount;
	fprintf(fout, "$L%d:\n", labelCount);
    printf("$L%d:\n", labelCount);
    printf("\n\tlabelStack: ");
    for (int i = 0; i <= labelTop; i++) {
        printf(" %d,", labels[i]);
    }
    printf("\n\n");
}

void labelWhileRepeat() {
    printf("labelWhileRepeat()\n");
	labelCount++;
 	fprintf(fout, "\tbeqz,\t %s,\t $L%d\n", stack[stackTop], labelCount);
 	printf("\tbeqz,\t %s,\t $L%d\n", stack[stackTop], labelCount);
 	labels[++labelTop] = labelCount;
    printf("\n\tlabelStack: ");
    for (int i = 0; i <= labelTop; i++) {
        printf(" %d,", labels[i]);
    }
    printf("\n\n");
}

void labelWhileFinish() {
    printf("labelWhileFinish()\n");
	int tmp1, tmp2;
	tmp2 = labels[labelTop--];
	tmp1 = labels[labelTop--];
	fprintf(fout, "\tjmp,\t $L%d\n$L%d:\n", tmp1, tmp2);
	printf("\tjmp,\t $L%d\n$L%d:\n", tmp1, tmp2);
	stackTop--;
    printf("\n\tlabelStack: ");
    for (int i = 0; i <= labelTop; i++) {
        printf(" %d,", labels[i]);
    }
    printf("\n\n");
}

// SymbolTable Functions
void checkPushSymbol(char * val) {
	char tmp[20];
//	strcpy(tmp, yytext);
    strcpy(tmp, val);
    printf("checking %s\n", tmp);
    printf("\n\tsymbolTable: %d\t", symbolTableCount);
    for (int i = 0; i < symbolTableCount; i++) {
        printf(" %s,", symbolTable[i].id);
    }
    printf("\n\n");
	int find = 0;
	for(int i = symbolTableCount - 1; i >= 0; i--) {
		if (!strcmp(symbolTable[i].id, tmp)) {
			find = 1;
			break;
		}
	}
	if (!find) {
        char op[35] = "Undeclared Variable ";
        strcat(op, tmp);
		yyerror(op);
		exit(0);
	}
    else {
        push(val);
    }
}

void setType() {
    printf("setType()\n");
	strcpy(tmpType, yytext);
}

void openScope() {
    printf("openScope()\n");
    //printf("symbolTable[%d].id: %s\n", symbolTableCount, symbolTable[symbolTableCount].id);
    strcpy(symbolTable[symbolTableCount].id, "newScope");
    symbolTableCount++;
}

void closeScope() {
    printf("closeScope()\n");
    for (int i = symbolTableCount; strcmp(symbolTable[i].id, "newScope") && strcmp(symbolTable[i].id, "globScope"); i--) {
        symbolTableCount--;
    }
}

void symbolDeclare(char * val) {
    printf("symbolDeclare() %s\n", val);
	char tmp[20];
	int find = 0;
//	strcpy(tmp, yytext);
	strcpy(tmp, val);
	for(int i = symbolTableCount - 1; i >= 0; i--) {
        if(!strcmp(symbolTable[i].id, "newScope")) break;
		if(!strcmp(symbolTable[i].id, tmp)) {
			find = 1;
			break;
		}
	}
	if(find) {
        char op[35] = "Redeclared Variable ";
        strcat(op, tmp);
		yyerror(op);
		exit(0);
	}
	else {
		strcpy(symbolTable[symbolTableCount].id, tmp);
		strcpy(symbolTable[symbolTableCount].type, tmpType);
		symbolTableCount++;
        printf("\n\tsymbolTable: ");
        for (int i = 0; i < symbolTableCount; i++) {
            printf(" %s,", symbolTable[i].id);
        }
        printf("\n\n");
        push(tmp);
	}
}

// FunctionTable Functions
void functionDeclare() {

}

void checkFunc() {

}

void call(){

}

int main(int argc, char *argv[]){
    yyin = fopen(argv[1], "r");
    fout = fopen("outFile", "w");

    strcpy(symbolTable[0].id, "globScope");
    strcpy(stack[0], "END");

    if(!yyparse()) printf("\n\tSuccessfully Compiled!\n\n");
    else {
		printf("\n\tParsing failed\n\n");
		exit(0);
    }

    fclose(yyin);
    fclose(fout);

    return 0;
}